import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import ListingCard from "@/components/ListingCard";
import { listings, verifiedWorkplaceIndex } from "@/data/catalog";

const slugify=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export async function generateStaticParams(){return verifiedWorkplaceIndex.map(x=>({slug:slugify(x.name)}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const w=verifiedWorkplaceIndex.find(x=>slugify(x.name)===slug);if(!w)return{};return{title:"PG near "+w.name+", Thane | PG Thane",description:"Find verified PG and shared-room accommodation options associated with "+w.name+" in "+w.location+", Thane.",alternates:{canonical:"https://www.pgthane.com/discover-pg-in-thane/workplace/"+slug}};}
export default async function WorkplacePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const w=verifiedWorkplaceIndex.find(x=>slugify(x.name)===slug);if(!w)notFound();const items=listings.filter(x=>x.published===true&&!x.photoOnly&&x.workplace.some(n=>n.toLowerCase()===w.name.toLowerCase()));return <main><header className="topbar"><Link className="brand" href="/">PG<span>Thane</span></Link><nav><Link href="/#locations">Locations</Link><Link href="/search">Search</Link><Link href="/#contact">Contact</Link></nav><a className="header-cta" href="tel:9892336705">Call</a></header><section className="location-hero"><div className="location-hero-inner"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/discover-pg-in-thane">PG in Thane</Link><span>/</span><strong>{w.name}</strong></div><div className="eyebrow">PG NEAR WORKPLACE</div><h1>PG near {w.name}, Thane</h1><p>{w.kind} · {w.location}</p><div className="location-actions"><a className="header-cta" href="tel:9892336705">Call 9892336705</a><a className="outline-cta" href="https://wa.me/919892336705">WhatsApp</a></div></div></section><section className="location-main"><div className="location-content"><div className="section-heading compact"><div><div className="eyebrow">VERIFIED DIRECTORY</div><h2>PG options near {w.name}</h2></div><p>{items.length?items.length+" verified PG options associated with this workplace.":"Verified PG options are being added. Search the wider area for current verified options."}</p></div>{items.length?<div className="listing-grid">{items.map(x=><ListingCard key={x.id} listing={x}/>)}</div>:<div className="empty-listings"><div className="empty-icon">⌂</div><h3>No verified PG listing is currently linked to this workplace</h3><p>We do not invent proximity, availability or property details. Search Hiranandani Estate for other verified options.</p><Link className="header-cta" href="/discover-pg-in-thane/pg-in-hiranandani-estate-thane">Browse Hiranandani Estate PGs</Link></div>}<div className="directory-panel"><div className="eyebrow">SEARCH</div><h3>Looking for another workplace?</h3><p>Search verified workplaces, microlocations and PG listings across Thane.</p><Link className="header-cta" href="/search?type=Workplace">Search workplaces</Link></div></div></section><footer><div className="brand">PG<span>Thane</span></div><p>PG · Paying Guest · Hostel · Shared Rooms in Thane</p><small>© {new Date().getFullYear()} PG Thane</small></footer></main>}